In [1]:
import cv2
import numpy as np
import random

agent_x, agent_y = 0, 350
gamma = 0.9

def create_env():
    obstacles=[
        (1,1),
        (4,1),
        (2,3),
        (5,3),
        (5,4),
        (5,5)
    ]
    
    canvas = np.zeros((400,400,3),dtype = np.uint8)
    
    for i in range(0,401,50):
        cv2.line(canvas,(0,i),(400,i),(255,255,255),1)
        cv2.line(canvas,(i,0),(i,400),(255,255,255),1)
    
    #cv2.rectangle(canvas,(agent_x+1,agent_y+1),(agent_x+50-1,agent_y+50-1),(255,0,0),-1)
    cv2.rectangle(canvas,(350,0),(400,50),(255,0,255),-1)

    for i in obstacles:
        x1 =[i[1]][0]*50
        y1 =[i[0]][0]*50
        x2 = x1+50
        y2 = y1+50
    
        cv2.rectangle(canvas,(x1,y1),(x2,y2),(0,255,255),-1)

    return canvas

canvas = create_env()

actions = {0:[0, -50], 1:[0, 50], 2:[-50, 0], 3:[50, 0]} # up,down,left,right

def env(state, action, agent_x, agent_y, b ,g, r):
    cv2.rectangle(state,(agent_x+1,agent_y+1),(agent_x+50-1,agent_y+50-1),(b ,g, r),-1)
    next_agent_x = actions[action][0] + agent_x
    next_agent_y = actions[action][1] + agent_y
    
    b, g, r = state[(next_agent_y+1+next_agent_y+50-1)//2,(next_agent_x+1+next_agent_x+50-1)//2,:]
    b, g, r = b.item(), g.item(), r.item()
    
    cv2.rectangle(state,(next_agent_x+1,next_agent_y+1),(next_agent_x+50-1,next_agent_y+50-1),(255,0,0),-1)
    reward = 0
    if b==0 and g==255 and r==255:
        reward = -100
    if b==255 and g==0 and r==255:
        reward = 100
    return state, next_agent_x, next_agent_y, b ,g, r, reward

# # up0,down1,left2,right3

# array([[ 0,  1,  2,  3,  4,  5,  6,  7],
#        [ 8,  9, 10, 11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20, 21, 22, 23],
#        [24, 25, 26, 27, 28, 29, 30, 31],
#        [32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47],
#        [48, 49, 50, 51, 52, 53, 54, 55],
#        [56, 57, 58, 59, 60, 61, 62, 63]])

def valid_actions(current_state):
    actions_list = [0, 1, 2, 3]
    if current_state==0:
        actions_list = [1, 3]
    elif current_state==7:
        actions_list = -1
    elif current_state==56:
        actions_list = [0, 3]
    elif current_state==63:
        actions_list = [0, 2]
    elif 1<=current_state<=6:
        actions_list = [1, 2, 3]
    elif 57<=current_state<=62:
        actions_list = [0, 2, 3]
    elif current_state%8==0 and current_state!=0 and current_state!=56:
        actions_list = [0, 1, 3]
    elif (current_state+1)%8==0 and current_state!=7 and current_state!=63:
        actions_list = [0, 1, 2]
    return actions_list

Q = np.zeros((64, 4))
b ,g, r = 0,0,0
reward = 0

for _ in range(10000):
    current_state = np.arange(64).reshape(8,8)[agent_y//50, agent_x//50]
    actions_list = valid_actions(current_state)
    if actions_list==-1:
        canvas = create_env()
        agent_x, agent_y = 0, 350
        reward = 0
        b, g, r = 0,0,0
        continue
    elif current_state in [9,19,33,43,44,45]:
        canvas = create_env()
        agent_x, agent_y = 0, 350
        reward = 0
        b, g, r = 0,0,0
        continue

    current_action = random.choice(actions_list)
    current_state_reward = reward

    canvas, agent_x, agent_y, b ,g, r, reward = env(canvas, current_action, agent_x, agent_y, b ,g, r)
    
    state_ = np.arange(64).reshape(8,8)[agent_y//50, agent_x//50]
    Q_ = Q[state_][np.argmax(Q[state_])]
    
    Q[current_state,current_action] = reward + gamma * Q_

#     cv2.imshow("Video", canvas)

#     # Press 'q' to quit
#     if cv2.waitKey(250) & 0xFF == ord('q'):
#         break

# cv2.destroyAllWindows()

In [2]:
canvas = create_env()
agent_x, agent_y = 0, 350
reward = 0
b, g, r = 0,0,0
for _ in range(10000):
    current_state = np.arange(64).reshape(8,8)[agent_y//50, agent_x//50]
    if current_state==7:
         break
    current_action = np.argmax(Q[current_state])
    
    canvas, agent_x, agent_y, b ,g, r, reward = env(canvas, current_action, agent_x, agent_y, b ,g, r)

    cv2.imshow("Video", canvas)

    # Press 'q' to quit
    if cv2.waitKey(250) & 0xFF == ord('q'):
        break
cv2.destroyAllWindows()

IndexError: index -425 is out of bounds for axis 0 with size 400

In [19]:
current_state#==7

np.int64(7)

In [30]:
cv2.destroyAllWindows()

In [15]:
np.arange(64).reshape(8,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [17]:
Q[48],Q[40]

(array([176.67370728, 143.1057029 ,   0.        , 128.115688  ]),
 array([142.35076445, 196.3041192 ,   0.        , 115.3041192 ]))