In [2]:
import torch
print(torch.__version__)

2.12.1+cu132


In [3]:
if torch.cuda.is_available():
    print("GpU")
    print(f"gpu:{torch.cuda.get_device_name(0)}")
else:
    print("cpu")

GpU
gpu:NVIDIA GeForce RTX 3050 6GB Laptop GPU


In [4]:
#Creating a Tensor

In [5]:
#using empty
a= torch.empty(2,3) #empty function allocating the memory and create space of 2,3
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#check type
type(a)

torch.Tensor

In [7]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(2,3)

tensor([[0.7993, 0.3123, 0.8137],
        [0.1533, 0.1367, 0.8930]])

In [10]:
#manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
#using tensor 
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
#other ways

#arrange

print("using arrange ->",torch.arange(0,10,2))  
# 2 is step

#linspace

print("using linspace ->", torch.linspace(0,10,10))

#using eye

print("using eye",torch.eye(5)) 
# eye for identity matrix

#using  full

print("using full - > " ,torch.full((3,3),5) )

using arrange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full - >  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [13]:
#tensor Shape 

In [14]:
x = torch.tensor ([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x , dtype=torch.float32) 

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [20]:
# find data type
x.dtype

torch.int64

In [21]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
#using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [24]:
# Data Type
# 32-bit Floating Point
# 64-bit Floating Point
# 16-bit Floating Point
# BFloat16  - > Brain floating-point format with reduced precision compared to float16. Used in mixed-precision training, especially on TPUs.
# 8-bit Floating Point
# 8-bit Integer
# 16-bit Integer
# 32-bit Integer
# 64-bit Integer
# 8-bit Unsigned Integer
# Boolean
# Complex 64  -> Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.
# Complex 128 - >  Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.
# Quantized Integer  -> Quantized signed 8-bit integer. Used in quantized models for efficient inference.
# Quantized Unsigned Integer - > Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.  




In [25]:
#  Mathematical Operations

In [26]:
# 1. Scalar operation 

In [27]:
x= torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [28]:
x+2
x-2
x*2
x/2
#int division
(x*100) // 3
#mod 
((x*100) // 3) %2
#power 
x**2


tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [29]:
a= torch.rand(2,3)
b=torch.rand(2,3)
print(a,b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]]) tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [30]:
#element wise
a+b
a+b
a*b
a/b
a ** b
a%b
a//b

tensor([[1., 0., 0.],
        [0., 0., 1.]])

In [31]:
c= torch.tensor([1,-2,3,-4])

In [32]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [33]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [34]:
d= torch.tensor([1.9,2.3,3.7,4.4,4.5,4.6])

In [35]:
#round
torch.round(d)

tensor([2., 2., 4., 4., 4., 5.])

In [36]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5., 5., 5.])

In [37]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4., 4., 4.])

In [38]:
#clamp
torch.clamp(d,2,3)

tensor([2.0000, 2.3000, 3.0000, 3.0000, 3.0000, 3.0000])

In [129]:
e = torch.randint(size=(2,3),low=0,high=10 , dtype=torch.float32)
e

tensor([[8., 4., 7.],
        [2., 3., 8.]])

In [130]:
#sum
torch.sum(e)

tensor(32.)

In [131]:
#sum along rows
torch.sum(e,dim=0)

tensor([10.,  7., 15.])

In [132]:
#sum along colums
torch.sum(e,dim=1)

tensor([19., 13.])

In [133]:
torch.mean(e)

tensor(5.3333)

In [135]:
torch.mean(e,dim=0)

tensor([5.0000, 3.5000, 7.5000])

In [136]:
torch.median(e)

tensor(4.)

In [138]:
torch .max(e)

tensor(8.)

In [139]:
torch.min(e)

tensor(2.)

In [142]:
#product
torch.prod(e)

tensor(10752.)

In [143]:
#standard deviation
torch.std(e)

tensor(2.6583)

In [144]:
#variance
torch.var(e)

tensor(7.0667)

In [146]:
#argmax
torch.argmax(e)

tensor(0)

In [147]:
#argmin
torch.argmin(e)

tensor(3)

In [150]:
f= torch.randint(size=(2,3),low=0,high=10)
g= torch.randint(size=(3,2),low=0,high=10)
print(f,g)

tensor([[4, 4, 1],
        [1, 2, 4]]) tensor([[7, 2],
        [5, 6],
        [1, 4]])


In [151]:
#matrix multiplication
torch.matmul(f,g)


tensor([[49, 36],
        [21, 30]])

In [152]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [154]:
#transpose
torch.transpose(f,0,1)

tensor([[4, 1],
        [4, 2],
        [1, 4]])

In [159]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[5., 6., 9.],
        [2., 3., 1.],
        [0., 2., 1.]])

In [160]:
#determinant
torch.det(h)

tensor(29.)

In [161]:
#inverse
torch.inverse(h)

tensor([[ 0.0345,  0.4138, -0.7241],
        [-0.0690,  0.1724,  0.4483],
        [ 0.1379, -0.3448,  0.1034]])

In [162]:
i = torch.randint(size=(2,3), low=0, high=10)
j= torch.randint(size=(2,3), low=0, high=10)

In [165]:
i<j
i>j
i==j
i!=j


tensor([[False, False, False],
        [False, False, False]])

In [173]:
k = torch.randint(size=(2,3), low=0, high=10,dtype=torch.float32)
k

tensor([[4., 6., 2.],
        [1., 0., 5.]])

In [174]:
torch.log(k)

tensor([[1.3863, 1.7918, 0.6931],
        [0.0000,   -inf, 1.6094]])

In [175]:
torch.exp(k)

tensor([[ 54.5981, 403.4288,   7.3891],
        [  2.7183,   1.0000, 148.4132]])

In [176]:
torch.sqrt(k)

tensor([[2.0000, 2.4495, 1.4142],
        [1.0000, 0.0000, 2.2361]])

In [177]:
torch.sigmoid(k)

tensor([[0.9820, 0.9975, 0.8808],
        [0.7311, 0.5000, 0.9933]])

In [178]:
torch.softmax(k,dim=0)

tensor([[0.9526, 0.9975, 0.0474],
        [0.0474, 0.0025, 0.9526]])

In [179]:
torch.relu(k)

tensor([[4., 6., 2.],
        [1., 0., 5.]])

In [181]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0015, 0.0813, 0.4907],
        [0.2130, 0.4603, 0.1386]])
tensor([[0.0277, 0.5662, 0.3503],
        [0.6555, 0.7667, 0.2269]])


In [182]:
m.add(n)

tensor([[0.0292, 0.6475, 0.8410],
        [0.8685, 1.2270, 0.3655]])

In [183]:
m

tensor([[0.0015, 0.0813, 0.4907],
        [0.2130, 0.4603, 0.1386]])

In [184]:
n

tensor([[0.0277, 0.5662, 0.3503],
        [0.6555, 0.7667, 0.2269]])

In [185]:
torch.relu(m)

tensor([[0.0015, 0.0813, 0.4907],
        [0.2130, 0.4603, 0.1386]])

In [188]:
m.relu_() #  _ -> implace operation

tensor([[0.0015, 0.0813, 0.4907],
        [0.2130, 0.4603, 0.1386]])

In [189]:
m

tensor([[0.0015, 0.0813, 0.4907],
        [0.2130, 0.4603, 0.1386]])

In [190]:
a = torch.rand(2,3)
a

tensor([[0.7555, 0.6458, 0.3673],
        [0.1770, 0.2966, 0.9925]])

In [192]:
b=a
b

tensor([[0.7555, 0.6458, 0.3673],
        [0.1770, 0.2966, 0.9925]])

In [196]:
a[0][0] =0
a

tensor([[0.0000, 0.6458, 0.3673],
        [0.1770, 0.2966, 0.9925]])

In [197]:
b

tensor([[0.0000, 0.6458, 0.3673],
        [0.1770, 0.2966, 0.9925]])

In [198]:
id(a)

1772904774176

In [199]:
id(b)

1772904774176

In [200]:
b=a.clone()

In [201]:
a

tensor([[0.0000, 0.6458, 0.3673],
        [0.1770, 0.2966, 0.9925]])

In [202]:
b

tensor([[0.0000, 0.6458, 0.3673],
        [0.1770, 0.2966, 0.9925]])

In [203]:
a[0][0]=10

In [204]:
a

tensor([[10.0000,  0.6458,  0.3673],
        [ 0.1770,  0.2966,  0.9925]])

In [205]:
b

tensor([[0.0000, 0.6458, 0.3673],
        [0.1770, 0.2966, 0.9925]])

In [206]:
id(a)

1772904774176

In [207]:
id(b)

1772904761696

In [208]:
#tensor operations on gpu


In [209]:
torch.cuda.is_available()

True

In [210]:
device=torch.device('cuda')

In [211]:
#creating a new tensor on gpu
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [213]:
#moving an existing tensor to gpu
a= torch.rand(2,3)
a

tensor([[0.2103, 0.1292, 0.1719],
        [0.9127, 0.6818, 0.1953]])

In [216]:
b=a.to(device)
b

tensor([[0.2103, 0.1292, 0.1719],
        [0.9127, 0.6818, 0.1953]], device='cuda:0')

In [217]:
b+5

tensor([[5.2103, 5.1292, 5.1719],
        [5.9127, 5.6818, 5.1953]], device='cuda:0')

In [220]:
import time

# Define the size of the matrices
size = 10000 # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # Matrix multiplication on CPU
cpu_time = time. time() - start_time

print(f"Time on CPU: {cpu_time: .4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on GPU
torch. cuda. synchronize() # Ensure all GPU operations are complete
gpu_time = time. time() - start_time

print(f"Time on GPU: {gpu_time :.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU:  12.9686 seconds
Time on GPU: 0.3189 seconds

Speedup (CPU time / GPU time): 40.66585326102396


In [222]:
#reshape
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [223]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [225]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [227]:
b=torch.rand(2,3,4)
b

tensor([[[0.2652, 0.8645, 0.8437, 0.1373],
         [0.1582, 0.8998, 0.9019, 0.7039],
         [0.2528, 0.5547, 0.0540, 0.7816]],

        [[0.8045, 0.3261, 0.2135, 0.0740],
         [0.1520, 0.8060, 0.6517, 0.3180],
         [0.1349, 0.3560, 0.5615, 0.2655]]])

In [229]:
#permute
b.permute(2,0,1)

tensor([[[0.2652, 0.1582, 0.2528],
         [0.8045, 0.1520, 0.1349]],

        [[0.8645, 0.8998, 0.5547],
         [0.3261, 0.8060, 0.3560]],

        [[0.8437, 0.9019, 0.0540],
         [0.2135, 0.6517, 0.5615]],

        [[0.1373, 0.7039, 0.7816],
         [0.0740, 0.3180, 0.2655]]])

In [230]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [235]:
 #unsqueese
#image size
c=torch.rand(266,266,3)
c.unsqueeze(0).shape

torch.Size([1, 266, 266, 3])

In [238]:
# squeeze
d= torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

In [239]:
#numpy and pytorch

In [241]:
import numpy as np


In [248]:
a= torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [249]:
b=a.numpy()
b

array([1, 2, 3])

In [250]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [251]:
torch.from_numpy(c)

tensor([1, 2, 3])